version: '3.1'

services:
    blocklister-manager:
        image: blocklist-manager:local
        restart: always
        environment:
            AWS_ACCESS_KEY_ID: redact
            AWS_SECRET_ACCESS_KEY: redact
            AWS_DEFAULT_REGION: redact
        ports:
          - 80:5000